export type Status = 
  | "Abgeschlossen"
  | "Ersatzteil Bestellt"
  | "Fertig Für Auslieferung"
  | "Gerät wird von Kunden Gebracht"
  | "Gerät wird von uns abgeholt"
  | "In Werkstatt-Prüfüng"
  | "";


export const STATUSES: { value: Status; label: string }[] = [
  { value: 'Abgeschlossen', label: 'Abgeschlossen' },
  { value: 'Ersatzteil Bestellt', label: 'Ersatzteil Bestellt' },
  { value: 'Fertig Für Auslieferung', label: 'Fertig Für Auslieferung' },
  { value: 'Gerät wird von Kunden Gebracht', label: 'Kunde bringt Gerät' },
  { value: 'Gerät wird von uns abgeholt', label: 'Abholung durch uns' },
  { value: 'In Werkstatt-Prüfüng', label: 'In Werkstatt-Prüfüng' },
];

export const TYPEN = [
  { value: 'KD', label: 'KD' },
  { value: 'Rkl', label: 'Rkl' },
];

export interface Customer {
  id?: string;
  name: string;
  adresse: string;
  telefon: string;
  gerät: string;
  problem: string;
  notiz: string;
  status: Status;
  datum: string;
  notizEditDate?: string;
  fehlercode?: string;
  typ?: string;
}

export const initialCustomers: Omit<Customer, 'id'>[] = [
  {
    "adresse": ",",
    "datum": "2025-07-21",
    "fehlercode": ",",
    "gerät": "Bosch Trockner",
    "name": "Keusenhoff",
    "notiz": "Kunde selbst gebracht. 25 nicht bez. 75-90 €",
    "notizEditDate": "21.07.2025",
    "problem": "Reinigung",
    "status": "Abgeschlossen",
    "telefon": "01784978094",
    "typ": "KD"
  },
  {
    "adresse": ",",
    "datum": "2025-07-21",
    "fehlercode": ",",
    "gerät": "Bosch Trockner",
    "name": "Keusenhoff",
    "notiz": "Kunde selbst gebracht. 25 nicht bez. 75-90 €\nGerät ist fertig. \n\n\nREINIGUNG 80+ Kunde informiert. Kommt abholen",
    "notizEditDate": "04.08.2025",
    "problem": "Reinigung",
    "status": "Abgeschlossen",
    "telefon": "01784978094",
    "typ": "KD"
  },
  {
    "adresse": "",
    "datum": "2025-07-26",
    "fehlercode": "",
    "gerät": "SM Miele",
    "name": "Keltenich",
    "notiz": "Kunde hat heute das Gerät zur Prüfung zurück gebracht.",
    "notizEditDate": "26.07.2025",
    "problem": "Fehler: Die Haussicherung fliegt \nbeim Start raus.",
    "status": "Abgeschlossen",
    "telefon": "017696248998",
    "typ": "Rkl"
  },
  {
    "adresse": "Köln",
    "datum": "2025-07-28",
    "fehlercode": "",
    "gerät": "AEG WM",
    "name": "Kepp",
    "notiz": "Gerät nicht bei uns gekauft!\nKunde bringt WM selbst.\nKunde MUSS \n\nnoch 10 Euro ZAHLEN !!!!\nDienstag fertig sein. 01784904588",
    "notizEditDate": "28.07.2025",
    "problem": "Maschine zieht Wasser, dann kein \n\nProgrammstart",
    "status": "In Werkstatt-Prüfüng",
    "telefon": "0221444611",
    "typ": "Rkl"
  },
  {
    "adresse": "Kyffhäuserstr 11, 50674 Köln",
    "datum": "2025-07-28",
    "fehlercode": "",
    "gerät": "Miele WM",
    "name": "Oblier",
    "notiz": "Pumpe repariert, liefern wir an Kunden zurück 02.08.25",
    "notizEditDate": "28.07.2025",
    "problem": "Pumpe",
    "status": "Abgeschlossen",
    "telefon": "01709057731",
    "typ": "KD"
  },
  {
    "adresse": "",
    "datum": "2025-07-30",
    "fehlercode": "",
    "gerät": "Induktionsfeld",
    "name": "Gruner",
    "notiz": "Heute hat Kunde das Feld gebracht zur Prüfung.\nWir rufen heute \n\nNachmittag zurück.",
    "notizEditDate": "31.07.2025",
    "problem": "Anzeige H was nicht weg geht.",
    "status": "Abgeschlossen",
    "telefon": "015175082591",
    "typ": "KD"
  },
  {
    "adresse": "",
    "datum": "2025-07-31",
    "fehlercode": "e25",
    "gerät": "SM Siemens",
    "name": "von Gahlen",
    "notiz": "Gerät hatte bereits 2 Fehler e15 und danach e17.\nVor erst 2 Tagen\n 29.07.wieder mit ausgetauschter Wasserpumpe zurück geliefert an \nKundin.",
    "notizEditDate": "31.07.2025",
    "problem": "Wasser wird nicht abgepumpt",
    "status": "",
    "telefon": "01783137365",
    "typ": "KD"
  },
  {
    "adresse": "Eupenerstr. 124, 50933 Köln",
    "datum": "2025-07-31",
    "fehlercode": "",
    "gerät": "Smeg gelb",
    "name": "SmartdeVision GmbH",
    "notiz": "Sehr viel Wasser ist auf den Fußboden gelaufen.\nHeute \nKundendienst vor Ort.",
    "notizEditDate": "31.07.2025",
    "problem": "Wassser ist ausgelaufen",
    "status": "Abgeschlossen",
    "telefon": "0177 7206515",
    "typ": "KD"
  },
  {
    "adresse": "",
    "datum": "2025-07-31",
    "fehlercode": "",
    "gerät": "Induktionsfeld",
    "name": "Gruner",
    "notiz": "Läuft einwandfrei bei uns in der Werkstatt. Kunde ist informiert \nund wird  das Feld wieder abholen.",
    "notizEditDate": "31.07.2025",
    "problem": "",
    "status": "Abgeschlossen",
    "telefon": "015175082591",
    "typ": "KD"
  },
  {
    "adresse": "Theeboldsgasse 14,50676 Köln",
    "datum": "2025-08-01",
    "fehlercode": "",
    "gerät": "WM/TR Samsung",
    "name": "Saleh (Mieterin)",
    "notiz": "Rechnung an Vermieter: Gerd Füssinger, Rebgasse 62, 79639 \n\nGrenzach- Wyhlen\n85 Euro zahlt Mieterin bei Abholung am 08.08.25",
    "notizEditDate": "04.09.2025",
    "problem": "Beim Einschalten läuft die Maschine\n\n\n kurz und geht dann nach kurzer\n \n\nZeit von alleine aus.",
    "status": "In Werkstatt-Prüfüng",
    "telefon": "015736451984",
    "typ": "KD"
  },
  {
    "adresse": "",
    "datum": "2025-08-01",
    "fehlercode": "",
    "gerät": "Induktionsfeld",
    "name": "Gruner",
    "notiz": "Kunde hat das Feld abgeholt.",
    "notizEditDate": "01.08.2025",
    "problem": "",
    "status": "Abgeschlossen",
    "telefon": "",
    "typ": "KD"
  },
  {
    "adresse": "Hellentahlerstr 5, 50937 Köln",
    "datum": "2025-08-02",
    "fehlercode": "H2o",
    "gerät": "Bauknecht WM",
    "name": "Malte Stoffers",
    "notiz": "Kunde ruft zurück um Abholtermin auszumachen nächste Woche.",
    "notizEditDate": "02.08.2025",
    "problem": "-Zu Beginn hat sie auffällig \ngeklackert, als die Trommel \nausgedreht ist. Das ist \nmittlerweile aber ein Stück \nweggegangen.\n-Ich konnte den \nWaschgang fortsetzen, danach lief \naber nur Wasser für mehrere Minuten\n nach und gleichzeitig ab, bis der \nFehler erneut angezeigt wurde.\n\nhttps://drive.google.com/drive/folders/1l9QBmR_-NfDaca4iec9Y6bYOvGpLWw3C?usp=sharing",
    "status": "Abgeschlossen",
    "telefon": "0177 601 8999",
    "typ": "Rkl"
  },
  {
    "adresse": "Hellentahlerstr 5, 50937 Köln",
    "datum": "2025-08-04",
    "fehlercode": "",
    "gerät": "Bauknecht WM",
    "name": "Malte Stoffers",
    "notiz": "Mit Kunden Abholtermin ausgemacht 07.08.25",
    "notizEditDate": "04.08.2025",
    "problem": "",
    "status": "Abgeschlossen",
    "telefon": "0177 601 8999",
    "typ": "Rkl"
  },
  {
    "adresse": "",
    "datum": "2025-08-04",
    "fehlercode": "",
    "gerät": "KGK Gorenje",
    "name": "Weber",
    "notiz": "kann von uns gegenüber abgeholt werde.",
    "notizEditDate": "04.08.2025",
    "problem": "Wieder kaputt",
    "status": "In Werkstatt-Prüfüng",
    "telefon": "015222947384",
    "typ": "Rkl"
  },
  {
    "adresse": "Alter Mühlenweg 53a, 50679 Köln",
    "datum": "2025-08-04",
    "fehlercode": "",
    "gerät": "KGK Liebherr",
    "name": "Bartel, Diana",
    "notiz": "05.08.25 Vor-Ort-Service Sefho+Fahrettin.\nAchtung das ist schon\n\n \n\nein Austauschgerät von uns!!!",
    "notizEditDate": "05.09.2025",
    "problem": "Kühlteil kühlt komplett nicht, \n\n\nGefrierteil arbeitet noch aber \n\n\nweniger.",
    "status": "In Werkstatt-Prüfüng",
    "telefon": "01782377262",
    "typ": "Rkl"
  },
  {
    "adresse": "Alter Mühlenweg 53a, 50679 Köln",
    "datum": "2025-08-07",
    "fehlercode": "",
    "gerät": "KGK Liebherr",
    "name": "Bartel, Diana",
    "notiz": "Kein Kundendienst vor Ort gemacht sondern Abholung von uns \nvereinbart für 07.08.25",
    "notizEditDate": "05.08.2025",
    "problem": "",
    "status": "In Werkstatt-Prüfüng",
    "telefon": "01782377262",
    "typ": "Rkl"
  },
  {
    "adresse": "Schätzingerstr. 30, 51107 Köln-Ostheim",
    "datum": "2025-08-06",
    "fehlercode": "",
    "gerät": "WM Miele",
    "name": "Ulsperger",
    "notiz": "Abholung beim Kunden 09.08.25",
    "notizEditDate": "06.08.2025",
    "problem": "Maschine \"Muffelt\" trotz Essig und \nSagrotan u Maschinenreiniger.",
    "status": "Abgeschlossen",
    "telefon": "015209442195",
    "typ": "Rkl"
  },
  {
    "adresse": "Augustastr.17,51065 Köln",
    "datum": "2025-08-07",
    "fehlercode": "F11",
    "gerät": "Miele SM",
    "name": "Springwald",
    "notiz": "Heute hat Kunde SM selber gebracht. Nur Überprüfen, nicht \n\nreparieren, erst Rücksprache mit Kunden",
    "notizEditDate": "08.08.2025",
    "problem": "Ablauf funktioniert nicht. Pumpt am\n Ende des Programms nicht ab.",
    "status": "Abgeschlossen",
    "telefon": "015787336951",
    "typ": "KD"
  },
  {
    "adresse": "Meschenicherstr. 449, 50997 Köln Godorf",
    "datum": "2025-08-07",
    "fehlercode": "",
    "gerät": "Gibson KGK",
    "name": "Peter Dissemond",
    "notiz": "Amerikanischeres Gerät, was mit deutschen Aggregaten umgerüstet \n\nist.\n11.08.25 um 11 Uhr Vor-Ort-Termin (Sefo). Kunde wurde \ninformiert, dass das Gerät zu uns in die Werkstatt muss, wie \nbereits vorher gesagt. Er will \nsich noch mal melden.",
    "notizEditDate": "14.08.2025",
    "problem": "Kühlt nicht mehr. Weiß/gelblicher \nAusfluss.",
    "status": "",
    "telefon": "01784551151",
    "typ": "KD"
  },
  {
    "adresse": "Neffeltalstr. 63, 52385 Embken",
    "datum": "2025-08-07",
    "fehlercode": "",
    "gerät": "Cube CC 165",
    "name": "Papst",
    "notiz": "07.08.25 Kundin hat Gerät heute gebracht zur Prüfung",
    "notizEditDate": "07.08.2025",
    "problem": "Hat keinen Strom",
    "status": "Abgeschlossen",
    "telefon": "01775691682",
    "typ": "Rkl"
  },
  {
    "adresse": "Theeboldsgasse 14,50676 Köln",
    "datum": "2025-08-08",
    "fehlercode": "",
    "gerät": "WM/TR Samsung",
    "name": "Saleh (Mieterin)",
    "notiz": "Heute abgeholt vom Kunden.",
    "notizEditDate": "08.08.2025",
    "problem": "",
    "status": "In Werkstatt-Prüfüng",
    "telefon": "015736451984",
    "typ": "KD"
  },
  {
    "adresse": "Augustastr.17,51065 Köln",
    "datum": "2025-08-08",
    "fehlercode": "",
    "gerät": "Miele SM",
    "name": "Springwald",
    "notiz": "Rückschlagventil ist defekt.\nKunde wurde informiert Reparatur \nkosten mit gebrauchten Ersatzteil 160,- mit neuen Ersatzteil \n240,-.\nKunde überlegt ein paar Tage was er macht.",
    "notizEditDate": "08.08.2025",
    "problem": "",
    "status": "Abgeschlossen",
    "telefon": "015787336951",
    "typ": "KD"
  },
  {
    "adresse": "",
    "datum": "2025-08-11",
    "fehlercode": "",
    "gerät": "SM Miele",
    "name": "Keltenich",
    "notiz": "Büronummer 02196762826\nKunde will wissen, ab noch was kaputt ist.",
    "notizEditDate": "11.08.2025",
    "problem": "",
    "status": "Abgeschlossen",
    "telefon": "017696248998",
    "typ": "Rkl"
  },
  {
    "adresse": "Reiherstr.29, 50997 Köln",
    "datum": "2025-08-11",
    "fehlercode": "",
    "gerät": "Siemens WM",
    "name": "Demerhan",
    "notiz": "13.08. wird Gerät abgeholt von uns. 85 Euro bereits heute bar \nbezahlt",
    "notizEditDate": "11.08.2025",
    "problem": "Ablaufproblem",
    "status": "Abgeschlossen",
    "telefon": "017657929446",
    "typ": "KD"
  },
  {
    "adresse": "Neffeltalstr. 63, 52385 Embken",
    "datum": "2025-08-11",
    "fehlercode": "",
    "gerät": "Cube CC 165",
    "name": "Papst",
    "notiz": "Fertig, Kunde holt morgen Gerät ab",
    "notizEditDate": "11.08.2025",
    "problem": "",
    "status": "Abgeschlossen",
    "telefon": "01775691682",
    "typ": "Rkl"
  },
  {
    "adresse": "",
    "datum": "2025-08-11",
    "fehlercode": "",
    "gerät": "KGK Gorenje",
    "name": "Weber",
    "notiz": "Anschlag der Tür auf andere Seite wechseln.",
    "notizEditDate": "11.08.2025",
    "problem": "",
    "status": "In Werkstatt-Prüfüng",
    "telefon": "015222947384",
    "typ": "Rkl"
  },
  {
    "adresse": "",
    "datum": "2025-08-12",
    "fehlercode": "",
    "gerät": "KGK Liebherr",
    "name": "bart",
    "notiz": "Kunde Zwischenstandmitgeteilt, das es Schwankungen gibt und nun\n \n\nAbdichtungen vorgenommen werden. Kunde angerufen und nicht \n\nerreicht am 05.09. Gerät ist fertig. Rücklieferung 08,09 Kunde \nhat angerufen.",
    "notizEditDate": "05.09.2025",
    "problem": "",
    "status": "Fertig Für Auslieferung",
    "telefon": "",
    "typ": "KD"
  },
  {
    "adresse": "Burgunderstr. 30, 50677 Köln",
    "datum": "2025-08-12",
    "fehlercode": "",
    "gerät": "KGK Gorenje",
    "name": "Weber",
    "notiz": "Kundin angerufen, informiert dass Gas nachgefüllt wurde. Kundin \n\nsagt, das wurde das letzte Mal auch gemacht und hielt nur einen \n\nTag. Deshalb genauer Checken. Morgen Mittag noch mal \n\ntelefonieren.",
    "notizEditDate": "12.08.2025",
    "problem": "",
    "status": "In Werkstatt-Prüfüng",
    "telefon": "015222947384",
    "typ": "Rkl"
  },
  {
    "adresse": "",
    "datum": "2025-08-12",
    "fehlercode": "",
    "gerät": "SM Miele",
    "name": "Keltenich",
    "notiz": "Kunden zurückgerufen: Kunde würde gerne reparierte Maschine am \nSamstag abholen.",
    "notizEditDate": "12.08.2025",
    "problem": "",
    "status": "Abgeschlossen",
    "telefon": "017696248998",
    "typ": "Rkl"
  },
  {
    "adresse": "Augustastr.17,51065 Köln",
    "datum": "2025-08-12",
    "fehlercode": "",
    "gerät": "Miele SM",
    "name": "Springwald",
    "notiz": "Kunde hat heute Gerät unrepariert abgeholt.",
    "notizEditDate": "12.08.2025",
    "problem": "",
    "status": "Abgeschlossen",
    "telefon": "015787336951",
    "typ": "KD"
  },
  {
    "adresse": "",
    "datum": "2025-08-12",
    "fehlercode": "",
    "gerät": "Herdplatte",
    "name": "Scharitsch, Frank",
    "notiz": "25 Euro bereits gezahlt für _Diagnose.",
    "notizEditDate": "13.08.2025",
    "problem": "Kabel angebrannt. Kabel komplett \nwechseln",
    "status": "Abgeschlossen",
    "telefon": "",
    "typ": "KD"
  },
  {
    "adresse": "",
    "datum": "2025-08-13",
    "fehlercode": "",
    "gerät": "Herdplatte",
    "name": "Scharitsch, Frank",
    "notiz": "Repariert 65,- +MWST und -25 Anzahlung",
    "notizEditDate": "13.08.2025",
    "problem": "",
    "status": "Fertig Für Auslieferung",
    "telefon": "",
    "typ": "KD"
  },
  {
    "adresse": "",
    "datum": "2025-08-13",
    "fehlercode": "",
    "gerät": "SM Miele",
    "name": "Keltenich",
    "notiz": "Im Kabelbaum war eine Leitung angeschmorgelt.\n15.oder 16.08. holt\n Kunde Maschine ab.",
    "notizEditDate": "13.08.2025",
    "problem": "Im Kabelbaum war eine Leitung \nangeschmorgelt.",
    "status": "Abgeschlossen",
    "telefon": "017696248998",
    "typ": "Rkl"
  },
  {
    "adresse": "Schätzingerstr. 30, 51107 Köln-Ostheim",
    "datum": "2025-08-13",
    "fehlercode": "",
    "gerät": "WM Miele",
    "name": "Ulsperger",
    "notiz": "14/08/ Auslieferung an Kunden, Kunde soll vor dem Haus einmal in \ndie Maschine riechen und sein ok geben.",
    "notizEditDate": "14.08.2025",
    "problem": "Maschine \"Muffelt\" immer noch!!! \nKunde hat hochgradige \nChlorallergie.",
    "status": "Abgeschlossen",
    "telefon": "015209442195",
    "typ": "Rkl"
  },
  {
    "adresse": "Reiherstr.29, 50997 Köln",
    "datum": "2025-08-14",
    "fehlercode": "",
    "gerät": "Siemens WM",
    "name": "Demerhan",
    "notiz": "Repariert Schlauch war ab u Grundreinigung.\n18/08/25 Auslieferung\n\n\n\n\n an Kunden\nRechnung geschrieben über 119,- muss noch bezahlt\n\n \n\n\nwerden in bar.18.08 Kunde hat 119,- in bar bezahlt",
    "notizEditDate": "18.08.2025",
    "problem": "",
    "status": "Abgeschlossen",
    "telefon": "017657929446",
    "typ": "KD"
  },
  {
    "adresse": "Theeboldsgasse 14,50676 Köln",
    "datum": "2025-08-14",
    "fehlercode": "",
    "gerät": "WM/TR Samsung",
    "name": "Saleh (Mieterin)",
    "notiz": "Kunde telefoniert. Elektronik-Problem, diese ist gegossen und \nkann nur teuer komplett ersetzt werden. Fragt den Vermieter wird\n \nsich melden.",
    "notizEditDate": "14.08.2025",
    "problem": "",
    "status": "In Werkstatt-Prüfüng",
    "telefon": "015736451984",
    "typ": "KD"
  },
  {
    "adresse": "Geisbergstr. 70, 560939 Köln",
    "datum": "2025-08-16",
    "fehlercode": "",
    "gerät": "SM AEG",
    "name": "Jochen Schäfer",
    "notiz": "85,- Gezahlt für Abholung und Check.\n18/08/25 Abholung von uns \nbeim Kunden",
    "notizEditDate": "16.08.2025",
    "problem": "Haussicherung fliegt raus, obwohl \ndas Gerät NICHT läuft. Gerät ca. 6 \nJahre alt.",
    "status": "Fertig Für Auslieferung",
    "telefon": "0160 8209614",
    "typ": "KD"
  },
  {
    "adresse": "",
    "datum": "2025-08-16",
    "fehlercode": "",
    "gerät": "Samsung WM",
    "name": "Aydenio",
    "notiz": "Kunde hat Gerät selber gebracht heute. 19/08/ Kunde informiert er\n\n kann das Gerät abholen.",
    "notizEditDate": "22.08.2025",
    "problem": "Zieht kein Wasser",
    "status": "Fertig Für Auslieferung",
    "telefon": "015772543770",
    "typ": "KD"
  },
  {
    "adresse": "Emmastr.4, 50937 Köln",
    "datum": "2025-08-18",
    "fehlercode": "",
    "gerät": "SM Miele",
    "name": "Baguio",
    "notiz": "Abholung von uns am 22/08/",
    "notizEditDate": "18.08.2025",
    "problem": "Gläser total verkalkt",
    "status": "In Werkstatt-Prüfüng",
    "telefon": "015758037492",
    "typ": "Rkl"
  },
  {
    "adresse": "Brambachstr.2,51069 Köln",
    "datum": "2025-08-18",
    "fehlercode": "",
    "gerät": "Neff Excellent S51N85XODE",
    "name": "Hambloch (Mieterin)",
    "notiz": "Vermieter Hamacher Gewerbeliegenschaft/KHV Kölner Hausverwaltung.\n\n\n14/08 vom Mieter abgeholt",
    "notizEditDate": "25.08.2025",
    "problem": "Es wird kein Wasser angezogen",
    "status": "Fertig Für Auslieferung",
    "telefon": "01737177977",
    "typ": "Rkl"
  },
  {
    "adresse": "Babarossaplatz 8, 50677 Köln",
    "datum": "2025-08-19",
    "fehlercode": "",
    "gerät": "WM",
    "name": "OHK",
    "notiz": "20/08/ wird WM geholt von uns. 21.08. Aquastopp ist gewechselt.\n \n\nWIr liefern zurück 29.08. offen 95€ (120-25)",
    "notizEditDate": "27.08.2025",
    "problem": "Aquastopp geht nicht ab, muss \ngewechselt werden.",
    "status": "Fertig Für Auslieferung",
    "telefon": "015778872877",
    "typ": "KD"
  },
  {
    "adresse": "Geisbergstr. 70, 560939 Köln",
    "datum": "",
    "fehlercode": "",
    "gerät": "SM AEG",
    "name": "Jochen Schäfer",
    "notiz": "19/08/ Kunde versucht anzurufen. Ging nicht dran.\nDer Stecker ist\n\n von unten komplett verschmorgelt. Gerät funktioniert. Die\n\n\nHaussteckdose muss dringend überprüft werden.",
    "notizEditDate": "22.08.2025",
    "problem": "",
    "status": "Fertig Für Auslieferung",
    "telefon": "0160 8209614",
    "typ": "KD"
  },
  {
    "adresse": "Paulstr. 16, 50676 Köln",
    "datum": "2025-08-19",
    "fehlercode": "F24",
    "gerät": "Miele SM",
    "name": "Dybowski",
    "notiz": "20.08. vor Ort-Service ausgemacht.28.08.holen wir das Gerät ab \nzur Reparatur.",
    "notizEditDate": "20.08.2025",
    "problem": "Fehler F24 und roch verschmort",
    "status": "Gerät wird von uns abgeholt",
    "telefon": "016099574315",
    "typ": "Rkl"
  },
  {
    "adresse": "Salierring45, 50677 Köln",
    "datum": "2025-08-20",
    "fehlercode": "",
    "gerät": "Miele TR",
    "name": "Krievet",
    "notiz": "Gerät ist nicht reparabel. Wird getauscht mit anderen Miele TR. \nHeute Lieferung",
    "notizEditDate": "20.08.2025",
    "problem": "",
    "status": "Abgeschlossen",
    "telefon": "0221216251",
    "typ": "Rkl"
  },
  {
    "adresse": "",
    "datum": "2025-08-20",
    "fehlercode": "",
    "gerät": "Miele WM",
    "name": "freisfeld",
    "notiz": "25 hat kunde bezahlt kunde hat gäret gebracht",
    "notizEditDate": "20.08.2025",
    "problem": "pumpt die ganze zeit ab und \nstreifen am electronic",
    "status": "Fertig Für Auslieferung",
    "telefon": "017655147567",
    "typ": "KD"
  },
  {
    "adresse": "Burgunderstr. 30, 50677 Köln",
    "datum": "2025-08-22",
    "fehlercode": "",
    "gerät": "KGK Gorenje",
    "name": "Weber",
    "notiz": "Motor ist kaputt, muss mit einem original Motor ausgetauscht \nwerden. Den haben wir nicht.\nKundin will kein 2. Austauschgerät. \nVIC was machen?",
    "notizEditDate": "22.08.2025",
    "problem": "",
    "status": "In Werkstatt-Prüfüng",
    "telefon": "015222947384",
    "typ": "Rkl"
  },
  {
    "adresse": "",
    "datum": "2025-08-22",
    "fehlercode": "",
    "gerät": "Miele WM",
    "name": "Balloni",
    "notiz": "Kunde hat Gerät gebracht.",
    "notizEditDate": "22.08.2025",
    "problem": "Tür geht immer wieder auf",
    "status": "Fertig Für Auslieferung",
    "telefon": "",
    "typ": "Rkl"
  },
  {
    "adresse": "",
    "datum": "2025-08-22",
    "fehlercode": "",
    "gerät": "Miele WM",
    "name": "Freisfeld",
    "notiz": "Heizstab gewechselt. Maschine funktioniert wieder. 137 €",
    "notizEditDate": "22.08.2025",
    "problem": "",
    "status": "Fertig Für Auslieferung",
    "telefon": "017655147567",
    "typ": "KD"
  },
  {
    "adresse": "Emmastr.4, 50937 Köln",
    "datum": "2025-08-22",
    "fehlercode": "",
    "gerät": "SM Miele",
    "name": "Baguio",
    "notiz": "Hatte keine 60€ bei der Abholung!!! offen 60 Euro",
    "notizEditDate": "22.08.2025",
    "problem": "",
    "status": "In Werkstatt-Prüfüng",
    "telefon": "015758037492",
    "typ": "Rkl"
  },
  {
    "adresse": "",
    "datum": "2025-08-22",
    "fehlercode": "",
    "gerät": "Miele WM",
    "name": "Balloni",
    "notiz": "Repariert, kann abgeholt werden, Kunde ist informiert.",
    "notizEditDate": "22.08.2025",
    "problem": "",
    "status": "Fertig Für Auslieferung",
    "telefon": "",
    "typ": "Rkl"
  },
  {
    "adresse": "",
    "datum": "2025-08-22",
    "fehlercode": "",
    "gerät": "AEG TR",
    "name": "Dirk",
    "notiz": "War vor 2 Monaten hier zur Reparatur. Nun Problem vermutlich \nKeilriemen.",
    "notizEditDate": "22.08.2025",
    "problem": "Keilriemen",
    "status": "Fertig Für Auslieferung",
    "telefon": "",
    "typ": "Rkl"
  },
  {
    "adresse": "Thieboldsgasse 23, 50676 Köln",
    "datum": "2025-08-23",
    "fehlercode": "",
    "gerät": "AfriCola Cube",
    "name": "Riebensahm",
    "notiz": "Samstag große Party, bitte schnell reparieren! Kunde hat Gerät \nselbst gebracht 23/08/",
    "notizEditDate": "23.08.2025",
    "problem": "Kühlt nicht, Licht geht",
    "status": "",
    "telefon": "01776759792",
    "typ": "Rkl"
  },
  {
    "adresse": "Jüssenstr.23a , 50827 Köln",
    "datum": "2025-08-23",
    "fehlercode": "",
    "gerät": "Miele WM",
    "name": "Freisfeld",
    "notiz": "Kunde wünscht nun Anlieferung 27/08/.\n152€ offen Zahlung bei \nLieferung (137-25+40)",
    "notizEditDate": "23.08.2025",
    "problem": "",
    "status": "Fertig Für Auslieferung",
    "telefon": "017655147567",
    "typ": "KD"
  },
  {
    "adresse": "Brühlerlandstr.454, 50997 Köln",
    "datum": "2025-08-23",
    "fehlercode": "",
    "gerät": "AEG Herd mit Ceran",
    "name": "Elke Axer",
    "notiz": "3. Mal Reklamation per Email Lüfter war schief",
    "notizEditDate": "02.09.2025",
    "problem": "die Umluft hat Aussetzer und macht \nGeräusche",
    "status": "Fertig Für Auslieferung",
    "telefon": "017673583015",
    "typ": "Rkl"
  },
  {
    "adresse": "",
    "datum": "2025-08-23",
    "fehlercode": "",
    "gerät": "AEG TR",
    "name": "Dirk",
    "notiz": "Filz war kaputt. Eigentlich keine RKL.\nGerät ist fertig.",
    "notizEditDate": "25.08.2025",
    "problem": "",
    "status": "Fertig Für Auslieferung",
    "telefon": "017660720603",
    "typ": "Rkl"
  },
  {
    "adresse": "Immendorferweg 1, 50968 Köln",
    "datum": "2025-08-25",
    "fehlercode": "",
    "gerät": "Miele TR",
    "name": "Klages",
    "notiz": "30.08. Abholung von uns. 85€ bei Abholung sind fällig. schlechter\n Kontakt zwischen Kohlen und Trommel geschliffen. Gerät wird am \n10.09.25 geliefert. Kunde muss 64,25 zahlen",
    "notizEditDate": "02.09.2025",
    "problem": "sicherung fliegt raus",
    "status": "Fertig Für Auslieferung",
    "telefon": "01603783565",
    "typ": "KD"
  },
  {
    "adresse": "",
    "datum": "2025-08-23",
    "fehlercode": "",
    "gerät": "Gastro SM",
    "name": "Reiche",
    "notiz": "22/08/ war Kunde hier, hat Bedienblende mitgenommen und will\n \n\n\n\n\nselber finden, den defekten Leiter Kunde hat Bedienblende \nam 03.09.25 selbst mitgebracht",
    "notizEditDate": "03.09.2025",
    "problem": "Bediendisplay funktioniert nicht \nalles",
    "status": "In Werkstatt-Prüfüng",
    "telefon": "01771913569",
    "typ": "Rkl"
  },
  {
    "adresse": "Geisbergstr. 70, 560939 Köln",
    "datum": "",
    "fehlercode": "",
    "gerät": "SM AEG",
    "name": "Jochen Schäfer",
    "notiz": "21/08/war Kunde da, Kabel gewechselt, gezahlt 77,35€. \n27/08/ \n\n\nAuslieferung an Kunden",
    "notizEditDate": "25.08.2025",
    "problem": "",
    "status": "Fertig Für Auslieferung",
    "telefon": "0160 8209614",
    "typ": "KD"
  },
  {
    "adresse": "Brambachstr.2,51069 Köln",
    "datum": "2025-08-23",
    "fehlercode": "",
    "gerät": "Neff Excellent S51N85XODE",
    "name": "Hambloch (Mieterin)",
    "notiz": "Die Umwelspumpe wird gewechselt.",
    "notizEditDate": "25.08.2025",
    "problem": "",
    "status": "Fertig Für Auslieferung",
    "telefon": "01737177977",
    "typ": "Rkl"
  },
  {
    "adresse": "Landsbergstr. 25, 50678 Köln",
    "datum": "2025-08-25",
    "fehlercode": "",
    "gerät": "Siemens SM",
    "name": "Siebdrat",
    "notiz": "12/08/25 erst geliefert. \n30/08/ holen wir die Maschine ab zur \nReparatur.",
    "notizEditDate": "25.08.2025",
    "problem": "Geschirr in der unteren Etage ist \nimmer dreckig und insgesamt wird \ndie Maschine nicht heiß. Das \nGeschirr ist immer kalt, \nklatschnass, und es tritt nach dem \nÖffnen kein Dampf aus.",
    "status": "Fertig Für Auslieferung",
    "telefon": "0176 22044834",
    "typ": "Rkl"
  },
  {
    "adresse": "Brambachstr.2,51069 Köln",
    "datum": "2025-08-25",
    "fehlercode": "",
    "gerät": "Neff Excellent S51N85XODE",
    "name": "Hambloch (Mieterin)",
    "notiz": "Maschine fertig.\nKunde angerufen.\n29/08/ Auslieferung an Kunden",
    "notizEditDate": "25.08.2025",
    "problem": "",
    "status": "Fertig Für Auslieferung",
    "telefon": "01737177977",
    "typ": "KD"
  },
  {
    "adresse": "",
    "datum": "",
    "fehlercode": "",
    "gerät": "Trockner AEG",
    "name": "Michels",
    "notiz": "Ist schon ein Austausch gewesen 170 Euro Gerät Keilriemen \n\n\n\n\n\ngetauscht kostenfrei",
    "notizEditDate": "01.09.2025",
    "problem": "Trocknet nicht\nAbholung 29,08,25 \n60€",
    "status": "Fertig Für Auslieferung",
    "telefon": "017647859815",
    "typ": "Rkl"
  },
  {
    "adresse": "",
    "datum": "2025-08-27",
    "fehlercode": "",
    "gerät": "samsung  herd Autark",
    "name": "kleinmanns",
    "notiz": "Steuerungselektronik defekt. Rep von uns nicht möglich unter 600€",
    "notizEditDate": "30.08.2025",
    "problem": "tut garnicks",
    "status": "Gerät wird von Kunden Gebracht",
    "telefon": "01774102551",
    "typ": "KD"
  },
  {
    "adresse": "paulstr.15-17",
    "datum": "2025-08-30",
    "fehlercode": "",
    "gerät": "miele wt",
    "name": "brandt",
    "notiz": "kunde mus 85 euro zahlen, Abholung 04.09.2025",
    "notizEditDate": "30.08.2025",
    "problem": "heitz nicht",
    "status": "Gerät wird von uns abgeholt",
    "telefon": "01796857084",
    "typ": "KD"
  },
  {
    "adresse": "Elsass Str.38  50677 Köln",
    "datum": "2025-09-01",
    "fehlercode": "pumpt\n\n nicht\n\n ab",
    "gerät": "Miele Classic W1",
    "name": "Berger",
    "notiz": "Abholung 05.09.25  85,-€",
    "notizEditDate": "01.09.2025",
    "problem": "pumpt nicht ab",
    "status": "In Werkstatt-Prüfüng",
    "telefon": "017630194276",
    "typ": "KD"
  },
  {
    "adresse": "Vernicher Str.1",
    "datum": "2025-09-02",
    "fehlercode": "",
    "gerät": "Kühlschrank Liebherr",
    "name": "Strox",
    "notiz": "",
    "notizEditDate": "02.09.2025",
    "problem": "kühlt nicht",
    "status": "",
    "telefon": "3406601 oder 3406568",
    "typ": "KD"
  },
  {
    "adresse": "Vernicher Str. 1, 50968 Köln",
    "datum": "2025-09-02",
    "fehlercode": "",
    "gerät": "Standherd Gorenje",
    "name": "Strox",
    "notiz": "KGS und Standherd wird am 08.09.2025 abgeholt Kunde muss 150,€ \n\nbei Abholung zahlen",
    "notizEditDate": "02.09.2025",
    "problem": "Unterhitze",
    "status": "",
    "telefon": "",
    "typ": "KD"
  },
  {
    "adresse": "",
    "datum": "",
    "fehlercode": "",
    "gerät": "",
    "name": "a",
    "notiz": "",
    "problem": "",
    "status": "",
    "telefon": "",
    "typ": "KD"
  },
  {
    "adresse": "",
    "datum": "",
    "fehlercode": "",
    "gerät": "",
    "name": "a",
    "notiz": "",
    "problem": "",
    "status": "",
    "telefon": "",
    "typ": "KD"
  },
  {
    "adresse": "Tacitusstr. 10, 50996 Köln",
    "datum": "2025-09-06",
    "fehlercode": "",
    "gerät": "Miele Trockner",
    "name": "Akurat / Sivritas",
    "notiz": "Gerät wird am 10.09.25 abgeholt. Kunde muss 60,-€ zahlen",
    "notizEditDate": "06.09.2025",
    "problem": "dreht sich nicht, komische \nGeräusche, stinkt verbrannt",
    "status": "Gerät wird von uns abgeholt",
    "telefon": "01755919278",
    "typ": "KD"
  },
  {
    "adresse": "gottesweg.175",
    "datum": "2025-09-08",
    "fehlercode": "",
    "gerät": "wm bauknecht",
    "name": "schmit",
    "notiz": "kunde zahlt 85 euro bei kollegen gäret wird am 11.09abgeholt",
    "notizEditDate": "08.09.2025",
    "problem": "schleudert nicht",
    "status": "",
    "telefon": "01782973930",
    "typ": "KD"
  },
  {
    "adresse": "",
    "datum": "",
    "fehlercode": "",
    "gerät": "becks ks",
    "name": "neuburg",
    "notiz": "",
    "problem": "kühlt nicht",
    "status": "",
    "telefon": "01734698268",
    "typ": "Rkl"
  }
];
